env:
  env_name: msd
  plant_data_path: data/msd/data.json
  env_cfg:
    w1: 0.1
    w2: 0.35
    w3: 0.55
    p_geom: 1.0e-3
    delta_t: 0
    n_mc: 2000
    q_prior: 0.05
    detector:
      alpha: 0.005
      g_tilde_override: 19.756
    beta:
      mode: lookup
      lookup_path: output/msd/beta_calibration/beta_lookup.npz
    beta_seed: 790

eval:
  # this is for normal simulation
  # out_dir: output/msd/simulation
  # this is for constant covariance evaluation
  # out_dir: output/msd/mean_U
  # this is for full evaluation with DynaMark
  # out_dir: output/msd/evaluate_lookup
  # this is for belief-adaptive evaluation
  out_dir: output/msd/nonrl_adaptive
  overwrite: true
  steps_env: 4000
  reps: 40
  base_seed: 129
  base_beta_seed: 678

runs:
  # ---- no watermark ----
  # - watermark: {mode: none}
  #   policy: {type: none}
  #   attack: {type: none}

  # - watermark: {mode: none}
  #   policy: {type: none}
  #   attack:
  #     type: replay
  #     onset_t: 1000
  #     replay:
  #       start_idx: 1000
  #       wrap: false
  #       history:
  #         mode: run_nominal_once
  #         seed: 123
  #         beta_seed: 223

  # ---- constant covariance baseline ----
  # - watermark:
  #     mode: constant_cov
  #     U: [[0.0117]]
  #   policy: {type: none}
  #   attack: {type: none}

  # - watermark:
  #     mode: constant_cov
  #     U: [[0.0117]]
  #   policy: {type: none}
  #   attack:
  #     type: replay
  #     onset_t: 1000
  #     replay:
  #       start_idx: 1000
  #       wrap: false
  #       history:
  #         mode: run_nominal_once
  #         seed: 12
  #         beta_seed: 223

  # ---- learned DDPG watermarking (uses U = cov_from_action(action)) ----
  # - watermark: {mode: from_action}
  #   policy:
  #     type: ddpg
  #     ckpt_dir: output/msd/train_lookup
  #     which: last
  #     explore: false
  #     device: cpu
  #   attack: {type: none}

  # - watermark: {mode: from_action}
  #   policy:
  #     type: ddpg
  #     ckpt_dir: output/msd/train_lookup
  #     which: last
  #     explore: false
  #     device: cpu
  #   attack:
  #     type: replay
  #     onset_t: 1000
  #     replay:
  #       start_idx: 1000
  #       wrap: false
  #       history:
  #         mode: run_nominal_once
  #         seed: 123
  #         beta_seed: 2233

  # ---- belief-adaptive linear policy ----
  - name: nonrl_adaptive_normal
    watermark: {mode: from_action}
    policy:
      type: nonrl_adaptive
      U_min: 1.08e-08
      U_max: 0.0404
    attack: {type: none}

  - name: nonrl_adaptive_replay
    watermark: {mode: from_action}
    policy:
      type: nonrl_adaptive
      U_min: 1.08e-08
      U_max: 0.0404
    attack:
      type: replay
      onset_t: 1000
      replay:
        start_idx: 1000
        wrap: false
        history:
          mode: run_nominal_once
          seed: 12
          beta_seed: 223